# <font color='black'>Title : ****Lab Manual Pratical 2****</font>

# <font color='black'> create one dimensional array</font>

In [3]:
import numpy as np

In [4]:
list=[20,40,60,80,100]

In [5]:
array=np.array(list)

In [6]:
array

array([ 20,  40,  60,  80, 100])

# <font color='black'> create 3x3 matrix range 2 to 10</font>

In [8]:
matrix= np.arange(2, 11).reshape(3, 3)

In [15]:
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# <font color='black'> append value end  of an array<font>

In [19]:
array1= np.array([1, 2, 3])
array2= np.array([4, 5, 6])
final_array=np.append(array1,array2)

In [21]:
final_array

array([1, 2, 3, 4, 5, 6])

# <font color='black'> create another shape array without changing data (3x2 to 2x3)<font>

In [26]:
array3= np.array([[1, 2], [3, 4], [5, 6]])
reshape= array3.reshape(2, 3)

In [28]:
reshape

array([[1, 2, 3],
       [4, 5, 6]])