In [1]:
import numpy as np

In [3]:
array=np.array([[3,4,5],
                [10,23,45],
               [22,35,56]])

In [14]:
mean_array=np.mean(array,axis=1)

In [18]:
mean_array

array([ 4.        , 26.        , 37.66666667])

In [20]:
standard_array=np.std(array, axis=1)

In [22]:
standard_array

array([ 0.81649658, 14.44529912, 14.00793426])

In [24]:
variance_array=np.var(array,axis=1)

In [28]:
variance_array

array([  0.66666667, 208.66666667, 196.22222222])